### ISSUE TITLE
pytorch version sample_code.py run error

### ISSUE THREAD

**Issue by plutoyuxie** [erezposner/Fast_Dense_Feature_Extraction#2]
Running method: allPatches on device: cuda:0
Total time for C_I: 0.01324005126953125sec
Averaged time for C_P per Patch without warm up: 0.0012916574080009014sec
------- Comparison between a base_net over all patches output and slim_net -------
aggregated difference percentage = 0.0000458457%
Traceback (most recent call last):
  File "d:/user/FE_pj/Fast_Dense_Feature_Extraction/sample_code.py", line 175, in <module>
    yi, xi = np.unravel_index(index, (imH, imW))
  File "<__array_function__ internals>", line 6, in unravel_index
ValueError: index 108153647 is out of bounds for array with size 1228800

**Comment by erezposner** [comment]
I will need more details. What image size are you using? did you set the dimensions properly?

**Comment by plutoyuxie** [comment]
Hi, thank you for the prompt response. I just use the sample script, nothing changed.
My pytorch version is 1.5, and cuda==10.1, win10

**Comment by plutoyuxie** [comment]
Hi, **'singlePatch'** mode works well. This issue only occurs in **'allPatches'** mode
Total time for C_I: 0.013318886756896972sec
Total time for C_P per Patch without warm up: 0.0009350776672363281sec
------- Comparison between a base_net single patch evaluation and slim_net -------
difference between the base_net & slim_net - 0.0000000000000

**Comment by erezposner** [comment]
please check the size of ```cropped_patches```

**Comment by plutoyuxie** [comment]
![image](https://user-images.githubusercontent.com/34409171/87649413-dadfd700-c782-11ea-9e37-282fc4e397f7.png)

**Comment by plutoyuxie** [comment]
slim_net_output_numpy.shape:           (113, 960, 1280) 
len(cropped_patches):                         1228800
cropped_patches[0].shape:                  torch.Size([1, 1, 15, 15])
base_net_output_per_patch.shape:      (113, 960, 1280)
cropped_batches.shape:                      torch.Size([10, 1, 15, 15])
y_base.shape:                                       torch.Size([10, 113, 1, 1])
base_current_output.shape:                (10, 113)
base_net_output_per_patch.shape:     (113, 960, 1280)
index:                                                  108153647
imH*imW:                                           1228800
base_net_output_per_patch.size:        138854400

**Comment by plutoyuxie** [comment]
It is solved by changing the line 177
ci, yi, xi = np.unravel_index(index, (slim_net.outChans, imH, imW))

**Comment by erezposner** [comment]
Changed these line. You can pull again
        index = np.argmax(sum(abs(base_net_output_per_patch - slim_net_output_numpy)))
        max_diff = np.max(sum(abs(base_net_output_per_patch - slim_net_output_numpy)))

**Comment by plutoyuxie** [comment]
Thanks a lot.

**Comment by plutoyuxie** [comment]
Hi, I have one more question. 
If my own network consists of  layers without striding or pooling, How do I transform Cp to Ci.
Does the function **multiConv** help?
@erezposner

**Comment by erezposner** [comment]
Please refer to the paper https://arxiv.org/pdf/1805.03096.pdf.
"In this paper,
we present an approach to compute patch-based local feature descriptors efficiently in
presence of pooling and striding layers for whole images at once"

This means that without pooling or stride layers there isn't any difference between Cp and Ci

**Comment by plutoyuxie** [comment]
I see, thanks.
