### ISSUE TITLE
This fast dense feature extraction method (FDFE) seems not equal to the common one in terms of different receptive field.

### ISSUE THREAD

**Issue by proteus1991** [erezposner/Fast_Dense_Feature_Extraction#4]
Hi,

I have a concern about the equality of the proposed method and the commonly used one. For example, if the image size is 240 * 240 and the patch size is 24 * 24, the receptive field of the commonly used method (i.e., extract all patches one by one from the whole image) would not exceed the patch size due to the fact that all patches are fed into the network independently for feature extraction. However, the receptive field of this FDFE seems to consider the region larger than 24 * 24 if the pooling operation is used.

Could you please explain why they are equal if we require the latent code (the results from feature extraction) is only generated from each fixed patch size (e.g., 24 * 24)?

Thanks,

Xiaohong

**Comment by proteus1991** [comment]
In my use case, the patch size is strictly limited to 24 * 24, which means the receptive field in CNN cannot exceed this size. Therefore, could you please enlighten me on how I can change your code accordingly to satisfy this requirement?

**Comment by erezposner** [comment]
The receptive field equals the patch size. The proposed method simply eliminates repeated calculations and does not change the receptive field.

You can also perform a simple experiment to evaluate the equality of the two approached and that is to inspect both outcomes.
