### ISSUE TITLE
Please check typo

### ISSUE THREAD

**Issue by hcw-00** [erezposner/Fast_Dense_Feature_Extraction#6]
![image](https://user-images.githubusercontent.com/39647373/94086181-2975b580-fe45-11ea-9a84-09e6ce52a757.png)

Hi,

Could you check typo in "Expected verbose"?

Total time for C_P => C_I ?

Averaged time for C_I => C_P ?

And why you do not compare Total time between two models?

Thank you.

**Comment by erezposner** [comment]
Where is the typo?

The verbose plotted in the verbose are for single patch run. And so, total time is per a single patch.
This makes the comparison apples to apples in this specific example.

**Comment by hcw-00** [comment]
Then I was misunderstood.
I'm getting to know about your work.
Thank you for your answer.

2020년 9월 24일 (목) 오후 7:38, Erez Posner <notifications@github.com>님이 작성:
